# Generated by Django 3.2.4 on 2022-04-12 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0002_message_isread'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='messenger_backend.conversation')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='messenger_backend.user')),
            ],
            options={
                'unique_together': {('userId', 'conversationId')},
            },
        ),
    ]
